# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-02 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='upload/'),
        ),
    ]
