# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-07-06 01:40
from __future__ import unicode_literals

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180702_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='result',
            field=models.CharField(default='late', max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='url',
            field=models.URLField(default='https://baike.baidu.com/pic/\u624b\u52a8\u6ed1\u7a3d/22206680/0/72f082025aafa40f05016cb4a764034f79f01997'),
        ),
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=account.models.upload_path),
        ),
    ]
